### PR TITLE
fixed metadata color

### LINKED ISSUE #37: Fix Metadata Colors
image

image

- Email, discord, GitHub should be gray

### PR DESCRIPTION
**Pull request by klevun7**
Screenshot 2024-11-04 at 12 06 21 AM

-changed text color to gray for email, github, and discord.

### CODE REVIEW

File: src/components/user/profile/header.tsx [hunk 1]
```diff
@@ -36,28 +36,32 @@ const Header = ({
...
+            className="text-starlight-gray"
             target="_blank"
           >
             {github}
           </Link>
         </div>
 
         <div className="flex items-center gap-2">
-          <FaDiscord className="h-5 w-5" />
+          <FaDiscord className="h-5 w-5 text-starlight-gray" />
```
Comment (shahdivyank) [inline src/components/user/profile/header.tsx]: place icons inside the link for all links

File: src/components/user/profile/header.tsx [hunk 2]
```diff
@@ -35,36 +35,36 @@ const Header = ({
...
-          <Mail className="h-5 w-5 text-starlight-gray" />
+        <div className="flex items-center">
           <Link
             href={`mailto:${email}`}
             className="text-starlight-gray"
             target="_blank"
           >
-            {email}
+            <Mail className="inline-block h-5 w-5 text-starlight-gray" />
+            <span className="ml-2">{email}</span>
```
Comment (klevun7) [inline src/components/user/profile/header.tsx:45]: used margin left in a separate span because icons weren't aligning but, not sure if this is the best way to do it.

**Review by shahdivyank — APPROVED** [review]
