### PR TITLE
Fix Admin Navigation Links

### LINKED ISSUE #49: Fix Admin Navigation Links
image

ignore "LEAD" in the picture.

on website, currently just has interview. add additional links to the admin navbar.

refer to routes in admin page
refer to /data/admin/navigation.tsx

### PR DESCRIPTION
**Pull request by zenxha**
Add Applications and Projects links to sidenav
* Closes #49

### CODE REVIEW

File: src/components/global/navigation/side.tsx [hunk 1]
```diff
@@ -21,7 +21,7 @@ const SideNav = ({ links }: props) => {
           <Link
             key={index}
             href={link}
-            className="!w-full hover:bg-starlight-yellow"
+            className="block !w-full hover:bg-starlight-yellow"
```
Comment (zenxha) [inline src/components/global/navigation/side.tsx]: Forced all link objects to act as block elements so that they newline correctly. Not sure if there's a better way to have it newline

**Comment by khandrew1** [comment]
add a photo of the site

**Comment by zenxha** [comment]
Screenshot 2024-11-04 at 10 22 08 AM
Screenshot 2024-11-04 at 10 22 31 AM
Screenshot 2024-11-04 at 10 23 17 AM
Nav Link components, Nav link hovered, Whole page

File: src/components/global/navigation/side.tsx (hunk 1 above)
Comment (khandrew1) [reply src/components/global/navigation/side.tsx]: `flex-col` on the container div should work? try that

**Review by khandrew1 — CHANGES_REQUESTED** [review]

**Review by shahdivyank — APPROVED** [review]
